/* automatically generated by rust-bindgen */

pub const STATUS_OK: STATUS = 0;
pub const STATUS_NOT_ENABLED: STATUS = 1;
pub const STATUS_NOT_RETURNED: STATUS = 2;
pub const STATUS_STALE: STATUS = 3;
pub type STATUS = u32;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct LocInfo {
    pub latitude: f64,
    pub longitude: f64,
    pub h_accuracy: ::std::os::raw::c_int,
    pub altitude: ::std::os::raw::c_int,
    pub v_accuracy: ::std::os::raw::c_int,
    pub status: STATUS,
    pub error_duration: ::std::os::raw::c_int,
}
extern "C" {
    pub fn run() -> LocInfo;
}
